### ISSUE TITLE
Update README to include requirements.

### ISSUE THREAD

**Issue by DevAseel** [zidhuss/muscat-tech.org#21]
**Description**

The existing README file lacks a section listing the requirements to run the app. Although the prerequisites are very minimal, it would be beneficial to include them for the sake of simplicity.

**Success Criteria**

Updated README file with the list of requirements.

**Comment by DevAseel** [comment]
@zidhuss Hey! Could you please give me access to contribute to the repository. Getting 403 when trying to push. 😁

**Comment by zidhuss** [comment]
Yeah we could definitely be clearer!

> @zidhuss Hey! Could you please give me access to contribute to the repository. Getting 403 when trying to push. 😁

You should first create a fork of the repository and push your changes there. You can then make a pull request from your fork to this repository. Check out [this page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) for the documentation on how to do that.

Thanks for your contribution!
